project: 
  type: website

website:
  title: "Jacob Holst - Computer Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/username/username.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Jacob Holst 2025Â©"
    right: 
      - icon: linkedin
        href: Your_LinkedIn_URL

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Algorithms"
        file: algorithms.qmd
      - text: "Data Science"
        file: ds.qmd
      - text: "Object-Oriented Programming"
        file: oop.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Other"
        file: other.qmd


  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Algorithms"
      style: "docked"
      background: light
      contents:
        - text: "Algorithms"
          file: algorithms.qmd
        - text: "---"
        # - text: "Project 1"
        #   file: Algorithms/project1.qmd
        # - text: "---"
        # - text: "Project 2"
        #   file: Algorithms/project2.qmd
        # - text: "---"
        # - text: "Project 3"
        #   file: Algorithms/project3.qmd
        # - text: "---"
        # - text: "Project 4"
        #   file: Algorithms/project4.qmd
        # - text: "---"
        # - text: "Project 5"
        #   file: Algorithms/project5.qmd
        # - text: "---"
    - title: "Data Science"
      style: "docked"
      background: light
      contents:
        - text: "Data Science"
          file: ds.qmd
        - text: "---"
        # - text: "Project 1"
        #   file: DS/project1.qmd
        # - text: "---"
        # - text: "Project 2"
        #   file: DS/project2.qmd
        # - text: "---"
        # - text: "Project 3"
        #   file: DS/project3.qmd
        # - text: "---"
        # - text: "Project 4"
        #   file: DS/project4.qmd
        # - text: "---"
        # - text: "Project 5"
        #   file: DS/project5.qmd
        # - text: "---"
    - title: "Object-Oriented Programming"
      style: "docked"
      background: light
      contents:
        - text: "Object-Oriented Programming"
          file: oop.qmd
        - text: "---"
        # - text: "Project 1"
        #   file: OOP/project1.qmd
        # - text: "---"
        # - text: "Project 2"
        #   file: OOP/project2.qmd
        # - text: "---"
        # - text: "Project 3"
        #   file: OOP/project3.qmd
        # - text: "---"
        # - text: "Project 4"
        #   file: OOP/project4.qmd
        # - text: "---"
        # - text: "Project 5"
        #   file: OOP/project5.qmd
        # - text: "---"
    - title: "Machine Learning"
      style: "docked"
      background: light
      contents:
        - text: "Machine Learning"
          file: ml.qmd
        - text: "---"
        # - text: "Project 1"
        #   file: Machine_Learning/project1.qmd
        # - text: "---"
        # - text: "Project 2"
        #   file: Machine_Learning/project2.qmd
        # - text: "---"
        # - text: "Project 3"
        #   file: Machine_Learning/project3.qmd
        # - text: "---"
        # - text: "Project 4"
        #   file: Machine_Learning/project4.qmd
        # - text: "---"
        # - text: "Project 5"
        #   file: Machine_Learning/project5.qmd
        # - text: "---"
    - title: "Full Stack"
      style: "docked"
      background: light
      contents:
        - text: "Full Stack"
          file: full_stack.qmd
        - text: "---"
        # - text: "Project 1"
        #   file: Full_Stack/project1.qmd
        # - text: "---"
        # - text: "Project 2"
        #   file: Full_Stack/project2.qmd
        # - text: "---"
        # - text: "Project 3"
        #   file: Full_Stack/project3.qmd
        # - text: "---"
        # - text: "Project 4"
        #   file: Full_Stack/project4.qmd
        # - text: "---"
        # - text: "Project 5"
        #   file: Full_Stack/project5.qmd
        # - text: "---"
    - title: "Other"
      style: "docked"
      background: light
      contents:
        - text: "Other"
          file: other.qmd
        - text: "---"

  
format:  
  html:
    theme:
      light: flatly
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true